name: Build and Save Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: '26.2'
          elixir-version: '1.15.7'

      - name: Install Dependencies
        run: mix deps.get

      - name: Build Release with Burrito
        run: MIX_ENV=prod mix release

      - name: Save Release to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            _build/prod/hamchron-*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
