name: Build and Save Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'New tag name'
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build Hamchron
    steps:
      - uses: actions/checkout@v3
      - run: git tag ${{ github.event.inputs.tag }}

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Install xz/7zip
        run: sudo apt-get install -y xz-utils p7zip-full

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26.0.2'
          elixir-version: '1.15.7'
      - run: mix deps.get

      - name: Compile Assets
        run: |
          mix assets.build
          mix assets.deploy

      - name: Build Release with Burrito
        run: MIX_ENV=prod mix release

      - name: Save Release to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            burrito_out/hamchron_*
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Release ${{ github.sha }}
          tag_name: ${{github.event.inputs.tag}}
          draft: false
          prerelease: false
