name: Build and Save Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    name: OTP / Elixir
    steps:
      - uses: actions/checkout@v3

      - name: Install xz/7zip
        run: sudo apt-get install -y xz-utils p7zip-full

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26.2'
          elixir-version: '1.15.7'
      - run: mix deps.get

      - name: Build Release with Burrito
        run: MIX_ENV=prod mix release

      - name: Save Release to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            _build/prod/hamchron-*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
